name: Build

on:
  push:
    tags:
      - "v*"
  pull_request:

jobs:
  build-linux-i386:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Linux (x86)
      run: |
        scripts/build-ubuntu-i386.sh
    - uses: actions/upload-artifact@v4
      with:
        name: hl2sbpp-linux-i386
        path: ./to-upload
        if-no-files-found: error

  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Linux (x86_64)
      run: |
        scripts/build-ubuntu-amd64.sh
    - uses: actions/upload-artifact@v4
      with:
        name: hl2sbpp-linux-amd64
        path: ./to-upload
        if-no-files-found: error

  build-android-armv7a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup cache dirs
        run: |
          mkdir -p ~/.gradle/caches
          mkdir -p ~/.gradle/wrapper
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "8"
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 8512546
          accept-android-sdk-licenses: true
      - name: Install Android SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
      - name: Add to PATH
        run: echo "PATH=$ANDROID_SDK_ROOT/build-tools/29.0.3:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV
      - name: Build ARMv7a
        run: scripts/build-android-armv7a.sh
      - uses: actions/upload-artifact@v4
        with:
          name: hl2sbpp-android-armv7a-libs
          path: srceng-mod-launcher/android
          if-no-files-found: error

  build-android-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup cache dirs
        run: |
          mkdir -p ~/.gradle/caches
          mkdir -p ~/.gradle/wrapper
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "8"
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 8512546
          accept-android-sdk-licenses: true
      - name: Install Android SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
      - name: Add to PATH
        run: echo "PATH=$ANDROID_SDK_ROOT/build-tools/29.0.3:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV
      - name: Build AArch64
        run: scripts/build-android-aarch64.sh
      - uses: actions/upload-artifact@v4
        with:
          name: hl2sbpp-android-aarch64-libs
          path: srceng-mod-launcher/android
          if-no-files-found: error

  build-android-apk:
    runs-on: ubuntu-latest
    needs: [build-android-armv7a, build-android-aarch64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "8"
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 8512546
          accept-android-sdk-licenses: true
      - name: Install Android SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
      - name: Add to PATH
        run: echo "PATH=$ANDROID_SDK_ROOT/build-tools/29.0.3:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV
      - name: Download ARMv7a libs
        uses: actions/download-artifact@v4
        with:
          name: hl2sbpp-android-armv7a-libs
          path: srceng-mod-launcher/android
      - name: Download AArch64 libs
        uses: actions/download-artifact@v4
        with:
          name: hl2sbpp-android-aarch64-libs
          path: srceng-mod-launcher/android
      - name: Build APK
        run: |
          scripts/build-apk.sh
          mv srceng-mod-launcher/build/android/mod-signed.apk hl2sbpp-release.apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hl2sbpp-release-apk
          path: hl2sbpp-release.apk
          if-no-files-found: error

  build-windows-win-i386:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Windows (x86)
      run: |
        ./waf.bat configure -T release --prefix=./win --disable-warns --build-game=hl2sbpp
        ./waf.bat install
    - uses: actions/upload-artifact@v4
      with:
        name: hl2sbpp-win-i386
        path: ./win
        if-no-files-found: error

  build-windows-win-amd64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Windows (x86_64)
      run: |
        ./waf.bat configure -T release --prefix=./win --disable-warns --build-game=hl2sbpp -8
        ./waf.bat install
    - uses: actions/upload-artifact@v4
      with:
        name: hl2sbpp-win-amd64
        path: ./win
        if-no-files-found: error

  build-dedicated-windows-i386:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Windows Dedicated (x86) 
      run: |
        ./waf.bat configure -T debug -d --prefix=./win --build-game=hl2sbpp
        ./waf.bat install
    - uses: actions/upload-artifact@v4
      with:
        name: hl2sbpp-win-dedicated-i386
        path: ./win
        if-no-files-found: error

  build-dedicated-windows-amd64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Windows Dedicated (x86_64)
      run: |
        ./waf.bat configure -T debug -d -8 --prefix=./win --build-game=hl2sbpp
        ./waf.bat install
    - uses: actions/upload-artifact@v4
      with:
        name: hl2sbpp-win-dedicated-amd64
        path: ./win
        if-no-files-found: error

  build-dedicated-linux-i386:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Linux Dedicated (x86)
      run: |
        scripts/build-ubuntu-i386.sh -d
    - uses: actions/upload-artifact@v4
      with:
        name: hl2sbpp-linux-dedicated-i386
        path: ./to-upload
        if-no-files-found: error

  build-dedicated-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Linux Dedicated (x86_64)
      run: |
        scripts/build-ubuntu-amd64.sh -d
    - uses: actions/upload-artifact@v4
      with:
        name: hl2sbpp-linux-dedicated-amd64
        path: ./to-upload
        if-no-files-found: error

  build-macos-amd64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build MacOS (x86_64)
      run: |
        scripts/build-macos-amd64.sh
    - uses: actions/upload-artifact@v4
      with:
        name: hl2sbpp-macos-amd64
        path: ./to-upload
        if-no-files-found: error

  build-dedicated-macos-amd64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build MacOS Dedicated (x86_64)
      run: |
        scripts/build-macos-amd64.sh -d
    - uses: actions/upload-artifact@v4
      with:
        name: hl2sbpp-macos-dedicated-amd64
        path: ./to-upload
        if-no-files-found: error
